title: "AbjadAuthorID"
description: "Shared Task on Abjad Authorship Identification (Multiclass Classification)"
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: "https://forms.gle/ZiYe9jSTuVRc7H9h9"
  repository_name: "Registration Open"
markdown:
  kramdown:
    auto_ids: false  # This disables automatic heading IDs

